"""005_portfolio_tables

Revision ID: 2c45d28eade6
Revises: 9c7b7e9860b1
Create Date: 2026-03-13 23:59:03.370684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c45d28eade6'
down_revision: Union[str, Sequence[str], None] = '9c7b7e9860b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('avg_cost_basis', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'ticker', name='uq_positions_portfolio_ticker')
    )
    op.create_table('transactions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', name='transaction_type_enum'), nullable=False),
    sa.Column('shares', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('transacted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('price_per_share > 0', name='ck_transactions_price_positive'),
    sa.CheckConstraint('shares > 0', name='ck_transactions_shares_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # Composite indexes for portfolio queries
    op.create_index(
        "ix_transactions_portfolio_ticker_date",
        "transactions",
        ["portfolio_id", "ticker", "transacted_at"],
    )
    op.create_index(
        "ix_positions_portfolio_ticker",
        "positions",
        ["portfolio_id", "ticker"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_positions_portfolio_ticker", table_name="positions")
    op.drop_index("ix_transactions_portfolio_ticker_date", table_name="transactions")
    op.drop_table('transactions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
