"""Verify bcrypt migration: old passlib hashes must still verify."""

import bcrypt

from backend.dependencies import hash_password, verify_password


class TestBcryptMigration:
    """Ensure backward compatibility after passlib removal."""

    def test_hash_returns_bcrypt_string(self) -> None:
        hashed = hash_password("testpass123")
        assert hashed.startswith("$2b$")

    def test_verify_correct_password(self) -> None:
        hashed = hash_password("mypassword")
        assert verify_password("mypassword", hashed) is True

    def test_verify_wrong_password(self) -> None:
        hashed = hash_password("mypassword")
        assert verify_password("wrongpassword", hashed) is False

    def test_verify_passlib_generated_hash(self) -> None:
        """A hash generated by passlib must still verify after migration."""
        passlib_hash = bcrypt.hashpw(b"testpassword", bcrypt.gensalt(rounds=12)).decode()
        assert verify_password("testpassword", passlib_hash) is True

    def test_different_passwords_produce_different_hashes(self) -> None:
        h1 = hash_password("password1")
        h2 = hash_password("password2")
        assert h1 != h2

    def test_same_password_produces_different_hashes(self) -> None:
        """Each call uses a new random salt."""
        h1 = hash_password("samepass")
        h2 = hash_password("samepass")
        assert h1 != h2
